services:
  expose:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - auth
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
      - .:/src

secrets:
  auth:
    file: ./auth.json